import {
  StethoscopeIcon,
  SparklesIcon,
  DropletIcon,
  SyringeIcon,
  ZapIcon,
  BoneIcon,
  EarIcon,
  HeartIcon,
} from "lucide-react";

export const doctors = [
  {
    id: 1,
    src: "/images/doctors/doc-sayapov.jpg",
    alt: "Саяпов Азат Глимзянович",
    name: "Саяпов Азат Глимзянович",
    designation: "Травматолог",
  },
  {
    id: 2,
    src: "/images/doctors/doc-valieva.jpg",
    alt: "Валиева Гузель Кавиевна",
    name: "Валиева Гузель Кавиевна",
    designation: "Акушер-гинеколог",
  },
  {
    id: 3,
    src: "/images/doctors/doc-golkov.jpg",
    alt: "Голков Семен Владимирович",
    name: "Голков Семен Владимирович",
    designation: "Хирург",
  },
  {
    id: 4,
    src: "/images/doctors/doc-zaharova.jpg",
    alt: "Захарова Лилия Насиховна",
    name: "Захарова Лилия Насиховна",
    designation: "Хирург-косметолог",
  },
  {
    id: 5,
    src: "/images/doctors/doc-saytaeva.jpg",
    alt: "Сайтаева Юлия Юрьевна",
    name: "Сайтаева Юлия Юрьевна",
    designation: "Педиатор",
  },
  {
    id: 6,
    src: "/images/doctors/doc-yadrennicova.jpg",
    alt: "Ядренникова Ирина Владимировна",
    name: "Ядренникова Ирина Владимировна",
    designation: "Кардиолог",
  },
  {
    id: 7,
    src: "/images/doctors/doc-shin.jpg",
    alt: "Шин Денис Александрович",
    name: "Шин Денис Александрович",
    designation: "Онколог",
  },
  {
    id: 8,
    src: "/images/doctors/doc-chekmarev.jpg",
    alt: "Чекмарев Алим Равильевич",
    name: "Чекмарев Алим Равильевич",
    designation: "Оториноларинголог",
  },
];

export const conferences = [
  {
    title: "Капельницы",
    icon: DropletIcon,
    subtitle: "Гиппократ",
    speakers: "Процедурный кабинет",
    buttonText: "Подробнее",
    buttonLink: "/services/drips",
  },
  {
    title: "Лазерное удаление новообразований",
    icon: SparklesIcon,
    subtitle: "Прием ведет",
    speakers: "Голков Семен Владимирович",
    buttonText: "Подробнее",
    buttonLink: "/services/laser-removal",
  },
  {
    title: "Сдача анализов",
    icon: SyringeIcon,
    subtitle: "Лаборатория",
    speakers: "KDL",
    buttonText: "Подробнее",
    buttonLink: "/services/lab",
  },
  {
    title: "Прием гинеколога",
    icon: HeartIcon,
    subtitle: "Прием ведет",
    speakers: "Валиева Гузель Кавиевна",
    buttonText: "Подробнее",
    buttonLink: "/services/gynecology",
  },
  {
    title: "Прием кардиолога",
    icon: HeartIcon,
    subtitle: "Прием ведет",
    speakers: "Ядренникова Ирина Владимировна",
    buttonText: "Подробнее",
    buttonLink: "/services/cardiology",
  },
  {
    title: "Прием онколога",
    icon: StethoscopeIcon,
    subtitle: "Прием ведет",
    speakers: "Шин Денис Александрович",
    buttonText: "Подробнее",
    buttonLink: "/services/oncology",
  },
  {
    title: "Прием оториноларинголога",
    icon: EarIcon,
    subtitle: "Прием ведет",
    speakers: "Чекмарев Алим Равилевич",
    buttonText: "Подробнее",
    buttonLink: "/services/lor",
  },
  {
    title: "Прием травматолога",
    icon: BoneIcon,
    subtitle: "Прием ведет",
    speakers: "Саяпов Азат Глимзянович",
    buttonText: "Подробнее",
    buttonLink: "/services/traumatology",
  },
  {
    title: "Радиоволновое удаление родинок",
    icon: ZapIcon,
    subtitle: "Прием ведет",
    speakers: "Захарова Лилия Насиховна",
    buttonText: "Подробнее",
    buttonLink: "/services/radiowave",
  },
  {
    title: "Услуги косметолога",
    icon: SparklesIcon,
    subtitle: "Прием ведет",
    speakers: "Захарова Лилия Насиховна",
    buttonText: "Подробнее",
    buttonLink: "/services/cosmetology",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Михайлов Д.А.",
    title: "Профессионал своего дела",
    text: "Обратился к Азату Глимзяновичу после спортивной травмы. Очень грамотный травматолог, назначил эффективное лечение. Через несколько недель уже вернулся к тренировкам. Спасибо за помощь!",
    rating: 5,
    image: "/images/doctors/doc-sayapov.jpg",
  },
  {
    id: 2,
    name: "Иванова А.К.",
    title: "Я нашла своего врача",
    text: "Я очень долго искала врача на ведение беременности и была так рада найти Гузель Кавиевну. Сама клиника комфортная, удобно расположена и недалеко от центра! Спасибо большое за такой опыт",
    rating: 5,
    image: "/images/doctors/doc-valieva.jpg",
  },
  {
    id: 3,
    name: "Королёв В.Н.",
    title: "Отличный хирург",
    text: "Делал операцию у Семена Владимировича. Все прошло отлично, послеоперационный период прошел без осложнений. Врач очень внимательный, все подробно объяснил перед операцией. Рекомендую!",
    rating: 5,
    image: "/images/doctors/doc-golkov.jpg",
  },
  {
    id: 4,
    name: "Сагитова Л.И.",
    title: "Я перестала бояться",
    text: "Огромное спасибо Лилии Насиховне за профессиональную работу. Долго подбирала косметолога, так как медицинское оброзование для меня было важным критерием! Врач очень деликатная, внимательная, процедуры прошли комфортно.",
    rating: 5,
    image: "/images/doctors/doc-zaharova.jpg",
  },
  {
    id: 5,
    name: "Николаева А.В.",
    title: "Лучший педиатр",
    text: "Юлия Юрьевна наблюдает моего ребенка с самого рождения. Всегда внимательная, грамотная, назначения действительно помогают. Ребенок не боится ходить к врачу. Очень благодарны за заботу!",
    rating: 5,
    image: "/images/doctors/doc-saytaeva.jpg",
  },
  {
    id: 6,
    name: "Степанов И.П.",
    title: "Надёжный кардиолог",
    text: "Ирина Владимировна помогла разобраться с проблемами сердца. Очень подробно все объяснила, назначила обследования и эффективное лечение. Давление пришло в норму, чувствую себя отлично. Спасибо!",
    rating: 5,
    image: "/images/doctors/doc-yadrennicova.jpg",
  },
  {
    id: 7,
    name: "Трофимов Р.С.",
    title: "Высококлассный специалист",
    text: "Очень благодарен Денису Александровичу за его профессионализм и чуткое отношение. Врач провел тщательную диагностику и назначил правильное лечение. Внимательный и знающий онколог. Рекомендую от всей души!",
    rating: 5,
    image: "/images/doctors/doc-shin.jpg",
  },
  {
    id: 8,
    name: "Федорова Е.Л.",
    title: "Наконец-то дышу свободно",
    text: "Долго мучилась с хроническим насморком, Алим Равильевич быстро нашел причину и вылечил. Прием прошел комфортно, врач все очень подробно рассказал. Огромное спасибо за профессиональную помощь!",
    rating: 5,
    image: "/images/doctors/doc-chekmarev.jpg",
  },
];
